-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 18:43:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `tb_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_endereco` ;

CREATE TABLE IF NOT EXISTS `tb_endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(30) NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tb_pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_pessoa` ;

CREATE TABLE IF NOT EXISTS `tb_pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nomePessoa` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `id_endereco` INT NOT NULL,
  PRIMARY KEY (`id_pessoa`),
  CONSTRAINT `fk_tb_pessoa_tb_endereco`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `tb_endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*CREATE INDEX `fk_tb_pessoa_tb_endereco_idx` ON `tb_pessoa` (`id_endereco` ASC) VISIBLE;*/


-- -----------------------------------------------------
-- Table `tb_funcao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_funcao` ;

CREATE TABLE IF NOT EXISTS `tb_funcao` (
  `id_funcao` INT NOT NULL,
  `nomeFuncao` VARCHAR(45) NOT NULL,
  `descricaoFuncao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_funcao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tb_funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_funcionario` ;

CREATE TABLE IF NOT EXISTS `tb_funcionario` (
  `matricula_funcionario` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(12) NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL,
  `dtNascimento` DATE NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(256) NOT NULL,
  `id_funcao` INT NOT NULL,
  `id_pessoa` INT NOT NULL,
  PRIMARY KEY (`matricula_funcionario`),
  CONSTRAINT `fk_tb_funcionario_tb_funcao1`
    FOREIGN KEY (`id_funcao`)
    REFERENCES `tb_funcao` (`id_funcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_funcionario_tb_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `tb_pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*CREATE INDEX `fk_tb_funcionario_tb_funcao1_idx` ON `tb_funcionario` (`id_funcao` ASC) VISIBLE;

CREATE INDEX `fk_tb_funcionario_tb_pessoa1_idx` ON `tb_funcionario` (`id_pessoa` ASC) VISIBLE;*/


-- -----------------------------------------------------
-- Table `tb_fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_fornecedor` ;

CREATE TABLE IF NOT EXISTS `tb_fornecedor` (
  `id_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_fornecedor`),
  CONSTRAINT `fk_tb_fornecedor_tb_pessoa1`
    FOREIGN KEY (`tb_pessoa_id_pessoa`)
    REFERENCES `tb_pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*CREATE INDEX `fk_tb_fornecedor_tb_pessoa1_idx` ON `tb_fornecedor` (`tb_pessoa_id_pessoa` ASC) VISIBLE;*/


-- -----------------------------------------------------
-- Table `tb_fornecedorJuridico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_fornecedorJuridico` ;

CREATE TABLE IF NOT EXISTS `tb_fornecedorJuridico` (
  `id_fornecedorJuridico` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(20) NOT NULL,
  `tb_fornecedor_id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`id_fornecedorJuridico`),
  CONSTRAINT `fk_tb_fornecedorJuridico_tb_fornecedor1`
    FOREIGN KEY (`tb_fornecedor_id_fornecedor`)
    REFERENCES `tb_fornecedor` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*CREATE INDEX `fk_tb_fornecedorJuridico_tb_fornecedor1_idx` ON `tb_fornecedorJuridico` (`tb_fornecedor_id_fornecedor` ASC) VISIBLE;*/


-- -----------------------------------------------------
-- Table `tb_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_cliente` ;

CREATE TABLE IF NOT EXISTS `tb_cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `saldo` DOUBLE NULL,
  `tb_pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  CONSTRAINT `fk_tb_cliente_tb_pessoa1`
    FOREIGN KEY (`tb_pessoa_id_pessoa`)
    REFERENCES `tb_pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*CREATE INDEX `fk_tb_cliente_tb_pessoa1_idx` ON `tb_cliente` (`tb_pessoa_id_pessoa` ASC) VISIBLE;*/


-- -----------------------------------------------------
-- Table `tb_clienteFisico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_clienteFisico` ;

CREATE TABLE IF NOT EXISTS `tb_clienteFisico` (
  `id_clienteFisico` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_clienteFisico`),
  CONSTRAINT `fk_tb_clienteFisico_tb_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `tb_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*CREATE INDEX `fk_tb_clienteFisico_tb_cliente1_idx` ON `tb_clienteFisico` (`id_cliente` ASC) VISIBLE;*/


-- -----------------------------------------------------
-- Table `tb_clienteJuridico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_clienteJuridico` ;

CREATE TABLE IF NOT EXISTS `tb_clienteJuridico` (
  `id_clienteJuridico` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(20) NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_clienteJuridico`),
  CONSTRAINT `fk_tb_clienteJuridico_tb_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `tb_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*CREATE INDEX `fk_tb_clienteJuridico_tb_cliente1_idx` ON `tb_clienteJuridico` (`id_cliente` ASC) VISIBLE;*/


-- -----------------------------------------------------
-- Table `tb_fornecedorFisico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_fornecedorFisico` ;

CREATE TABLE IF NOT EXISTS `tb_fornecedorFisico` (
  `id_fornecedorFisico` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `tb_fornecedor_id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`id_fornecedorFisico`),
  CONSTRAINT `fk_tb_fornecedorFisico_tb_fornecedor1`
    FOREIGN KEY (`tb_fornecedor_id_fornecedor`)
    REFERENCES `tb_fornecedor` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*CREATE INDEX `fk_tb_fornecedorFisico_tb_fornecedor1_idx` ON `tb_fornecedorFisico` (`tb_fornecedor_id_fornecedor` ASC) VISIBLE;*/


-- -----------------------------------------------------
-- Table `tb_servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_servico` ;

CREATE TABLE IF NOT EXISTS `tb_servico` (
  `id_servico` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `tipoServico` VARCHAR(45) NULL,
  `metragemQuadrada` VARCHAR(45) NULL,
  `metragemLinear` VARCHAR(45) NULL,
  `valorServico` DOUBLE NULL,
  PRIMARY KEY (`id_servico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tb_venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_venda` ;

CREATE TABLE IF NOT EXISTS `tb_venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `dataVenda` DATE NOT NULL,
  `precoVenda` DOUBLE NOT NULL,
  `desconto` DOUBLE NULL,
  `valorTotal` DOUBLE NOT NULL,
  `id_funcionario` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_servico` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  CONSTRAINT `fk_tb_venda_tb_funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `tb_funcionario` (`matricula_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_venda_tb_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `tb_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_venda_tb_servico1`
    FOREIGN KEY (`id_servico`)
    REFERENCES `tb_servico` (`id_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*CREATE INDEX `fk_tb_venda_tb_funcionario1_idx` ON `tb_venda` (`id_funcionario` ASC) VISIBLE;

CREATE INDEX `fk_tb_venda_tb_cliente1_idx` ON `tb_venda` (`id_cliente` ASC) VISIBLE;

CREATE INDEX `fk_tb_venda_tb_servico1_idx` ON `tb_venda` (`id_servico` ASC) VISIBLE;*/


-- -----------------------------------------------------
-- Table `tb_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_compra` ;

CREATE TABLE IF NOT EXISTS `tb_compra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `dataCompra` DATE NOT NULL,
  `valorCompra` DOUBLE NOT NULL,
  `id_funcionario` INT NOT NULL,
  `id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`id_compra`),
  CONSTRAINT `fk_tb_compra_tb_funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `tb_funcionario` (`matricula_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_compra_tb_fornecedor1`
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `tb_fornecedor` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*CREATE INDEX `fk_tb_compra_tb_funcionario1_idx` ON `tb_compra` (`id_funcionario` ASC) VISIBLE;

CREATE INDEX `fk_tb_compra_tb_fornecedor1_idx` ON `tb_compra` (`id_fornecedor` ASC) VISIBLE;*/


-- -----------------------------------------------------
-- Table `tb_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_produto` ;

CREATE TABLE IF NOT EXISTS `tb_produto` (
  `cod_produto` INT NOT NULL,
  `nomeProduto` VARCHAR(45) NOT NULL,
  `codigoBarra` VARCHAR(45) NOT NULL,
  `corProduto` VARCHAR(45) NOT NULL,
  `notaFiscal` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tb_itemVendido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_itemVendido` ;

CREATE TABLE IF NOT EXISTS `tb_itemVendido` (
  `id_itemVendido` INT NOT NULL AUTO_INCREMENT,
  `precoVenda` DOUBLE NOT NULL,
  `quantidadeVenda` INT NOT NULL,
  `id_venda` INT NOT NULL,
  `cod_produto` INT NOT NULL,
  PRIMARY KEY (`id_itemVendido`),
  CONSTRAINT `fk_tb_itensVendidos_tb_venda1`
    FOREIGN KEY (`id_venda`)
    REFERENCES `tb_venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_itemVendido_tb_produto1`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `tb_produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*CREATE INDEX `fk_tb_itensVendidos_tb_venda1_idx` ON `tb_itemVendido` (`id_venda` ASC) VISIBLE;

CREATE INDEX `fk_tb_itemVendido_tb_produto1_idx` ON `tb_itemVendido` (`cod_produto` ASC) VISIBLE;*/


-- -----------------------------------------------------
-- Table `tb_itemComprado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_itemComprado` ;

CREATE TABLE IF NOT EXISTS `tb_itemComprado` (
  `id_itemComprado` INT NOT NULL,
  `precoCompra` DOUBLE NOT NULL,
  `quantidade` INT NOT NULL,
  `id_compra` INT NOT NULL,
  `cod_produto` INT NOT NULL,
  PRIMARY KEY (`id_itemComprado`),
  CONSTRAINT `fk_tb_itensComprados_tb_compra1`
    FOREIGN KEY (`id_compra`)
    REFERENCES `tb_compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_itemComprado_tb_produto1`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `tb_produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*CREATE INDEX `fk_tb_itensComprados_tb_compra1_idx` ON `tb_itemComprado` (`id_compra` ASC) VISIBLE;

CREATE INDEX `fk_tb_itemComprado_tb_produto1_idx` ON `tb_itemComprado` (`cod_produto` ASC) VISIBLE;*/


-- -----------------------------------------------------
-- Table `tb_estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_estoque` ;

CREATE TABLE IF NOT EXISTS `tb_estoque` (
  `id_estoque` INT NOT NULL AUTO_INCREMENT,
  `cod_produto` INT NOT NULL,
  `qtdMinima` INT NOT NULL,
  `qtdMaxima` INT NOT NULL,
  `qtdAtual_Disponivel` INT NOT NULL,
  `qtdReal` INT NOT NULL,
  PRIMARY KEY (`id_estoque`),
  CONSTRAINT `fk_tb_estoque_tb_produto1`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `tb_produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*CREATE INDEX `fk_tb_estoque_tb_produto1_idx` ON `tb_estoque` (`cod_produto` ASC) VISIBLE;*/


-- -----------------------------------------------------
-- Table `tb_acessorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_acessorio` ;

CREATE TABLE IF NOT EXISTS `tb_acessorio` (
  `id_acessorio` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `cor` VARCHAR(45) NULL,
  `tb_produto_cod_produto` INT NOT NULL,
  PRIMARY KEY (`id_acessorio`),
  CONSTRAINT `fk_tb_acessorio_tb_produto1`
    FOREIGN KEY (`tb_produto_cod_produto`)
    REFERENCES `tb_produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*CREATE INDEX `fk_tb_acessorio_tb_produto1_idx` ON `tb_acessorio` (`tb_produto_cod_produto` ASC) VISIBLE;
*/

-- -----------------------------------------------------
-- Table `tb_vidro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_vidro` ;

CREATE TABLE IF NOT EXISTS `tb_vidro` (
  `id_vidro` INT NOT NULL,
  `largura` VARCHAR(45) NULL,
  `altura` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `tb_produto_cod_produto` INT NOT NULL,
  PRIMARY KEY (`id_vidro`),
  CONSTRAINT `fk_tb_vidro_tb_produto1`
    FOREIGN KEY (`tb_produto_cod_produto`)
    REFERENCES `tb_produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*CREATE INDEX `fk_tb_vidro_tb_produto1_idx` ON `tb_vidro` (`tb_produto_cod_produto` ASC) VISIBLE;*/


-- -----------------------------------------------------
-- Table `tb_aluminio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_aluminio` ;

CREATE TABLE IF NOT EXISTS `tb_aluminio` (
  `id_aluminio` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `tb_produto_cod_produto` INT NOT NULL,
  PRIMARY KEY (`id_aluminio`),
  CONSTRAINT `fk_tb_aluminio_tb_produto1`
    FOREIGN KEY (`tb_produto_cod_produto`)
    REFERENCES `tb_produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*CREATE INDEX `fk_tb_aluminio_tb_produto1_idx` ON `tb_aluminio` (`tb_produto_cod_produto` ASC) VISIBLE;*/


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
